### ISSUE TITLE
Pinpoint Deprecated = Location Module Issues

### ISSUE THREAD

**Issue by danner26** [munkireport/location#1]
Hey everyone,

Now that upgrade season is coming to an end I have more time to work on MR and what not.. in light of recent 10.13 updates, we cannot automatically enable location services and for that reason pinpoint is deprecated.

Therefore our location module is hereby in trouble.. I am researching other methods, but does anyone have any ideas? I figured I would start a thread to look into this issue..

**Comment by jelockwood** [comment]
@bochoven 
Your Wiki here - 
[
https://github.com/munkireport/munkireport-php/wiki/Modules](https://github.com/munkireport/munkireport-php/wiki/Modules) still refers to the deprecated Clayton authored version of pinpoint. You are welcome indeed encouraged to point people to my replacement.

:)

**Comment by bochoven** [comment]
Please feel free to update that, the wiki is open for anyone to edit!

**Comment by jelockwood** [comment]
@bochoven 
I have successfully updated the Wiki page but I am not sure I was able to update the README at 

https://github.com/munkireport/location/blob/master/README.md

The first few lines need changing, suggested change is as follows.


Provides location information on where a Mac is physical located.

~~This module relies on pinpoint an external project located here: https://github.com/clburlison/pinpoint~~

~~Author: Clayton Burlison - https://clburlison.com~~

This module relies on pinpoint an external project located here: https://github.com/jelockwood/pinpoint

Author: John Lockwood

(I have never before tried to 'commit' a change to someone else's repo.)

**Comment by bochoven** [comment]
Hi John, you can edit the README on GitHub, if you try to save, GitHub will help you make a Pull Request out of your edits.

**Comment by jelockwood** [comment]
Yes I saw how to do that but that makes a fork on my account and does not commit the change to your version. Hence only I see the change to the README.

**Comment by bochoven** [comment]
You can create a pull request out of your fork.
