### ISSUE TITLE
google.maps.Marker is deprecated

### ISSUE THREAD

**Issue by precursorca** [munkireport/location#7]
The module uses js/marketclusterer.js

This is a v3 implementation of the
 * <a href="http://gmaps-utility-library-dev.googlecode.com/svn/tags/markerclusterer/"
 * >v2 MarkerClusterer</a>.

As of February 21st, 2024 (v3.56), google.maps.Marker is deprecated. We encourage you to transition to the new google.maps.marker.AdvancedMarkerElement class. Advanced markers provide substantial improvements over the legacy google.maps.Marker class. The minimum version of the Maps JavaScript API with google.maps.marker.AdvancedMarkerElement is 3.53.2. At this time, google.maps.Marker is not scheduled to be discontinued.

See: https://developers.google.com/maps/documentation/javascript/markers

To update a legacy marker to be an advanced marker, take the following steps:
1. Add code to import the marker library. Note that the previous version of markers (google.maps.Marker) does not have this requirement.
2. Change google.maps.Marker to google.maps.marker.AdvancedMarkerElement
3. Add a map ID to your map initialization code. For example mapId: 'DEMO_MAP_ID' for testing purposes if you don't have a map ID already.

**Comment by precursorca** [comment]
As it is not scheduled to be discontinued perhaps this is not much of an issue.

**Comment by bochoven** [comment]
Fixed by #8
